// <auto-generated />
using System;
using Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(SchoolBusDB))]
    [Migration("20231106115741_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1430),
                            Password = "admin",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1430),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(795),
                            DriverId = 1,
                            Number = "01-AA-001",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(796)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 18,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(798),
                            DriverId = 2,
                            Number = "02-BB-002",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(799)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(800),
                            DriverId = 3,
                            Number = "03-CC-003",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(801)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 22,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(803),
                            DriverId = 4,
                            Number = "04-DD-004",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(803)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(805),
                            DriverId = 5,
                            Number = "05-EE-005",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(805)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 21,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(807),
                            DriverId = 6,
                            Number = "06-FF-006",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(807)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 28,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(809),
                            DriverId = 7,
                            Number = "07-GG-007",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(810)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 24,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(811),
                            DriverId = 8,
                            Number = "08-HH-008",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(812)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 19,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(813),
                            DriverId = 9,
                            Number = "09-II-009",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(814)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 15,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(816),
                            DriverId = 10,
                            Number = "10-JJ-010",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(816)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1512),
                            Name = "ZU-051",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1512)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1514),
                            Name = "ZU-052",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1514)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1516),
                            Name = "ZU-053",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1517)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1518),
                            Name = "ZU-054",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1519)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1520),
                            Name = "ZU-055",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1521)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1522),
                            Name = "ZU-056",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1523)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1525),
                            Name = "ZU-057",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1525)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1527),
                            Name = "ZU-058",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1527)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1529),
                            Name = "ZU-059",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1529)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1531),
                            Name = "ZU-060",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1531)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1739),
                            FirstName = "Daniel",
                            LastName = "Cormier",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1739)
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1741),
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1742)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1744),
                            FirstName = "Emily",
                            LastName = "Smith",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1744)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1746),
                            FirstName = "John",
                            LastName = "Brown",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1747)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1749),
                            FirstName = "Olivia",
                            LastName = "Miller",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1749)
                        },
                        new
                        {
                            Id = 6,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1751),
                            FirstName = "Lucas",
                            LastName = "Davis",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1752)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1754),
                            FirstName = "Ava",
                            LastName = "Garcia",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1754)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1757),
                            FirstName = "Liam",
                            LastName = "Martinez",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1757)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1760),
                            FirstName = "Mia",
                            LastName = "Clark",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1760)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1763),
                            FirstName = "Noah",
                            LastName = "Taylor",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1764)
                        },
                        new
                        {
                            Id = 11,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1766),
                            FirstName = "Sophia",
                            LastName = "Walker",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1767)
                        },
                        new
                        {
                            Id = 12,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1774),
                            FirstName = "William",
                            LastName = "White",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1775)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1777),
                            FirstName = "Emma",
                            LastName = "Jones",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1777)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1779),
                            FirstName = "James",
                            LastName = "Wilson",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1779)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1782),
                            FirstName = "Isabella",
                            LastName = "Jackson",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1782)
                        },
                        new
                        {
                            Id = 16,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1784),
                            FirstName = "Benjamin",
                            LastName = "Harris",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1785)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1786),
                            FirstName = "Lucy",
                            LastName = "Turner",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1787)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1789),
                            FirstName = "Logan",
                            LastName = "Smith",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1790)
                        },
                        new
                        {
                            Id = 19,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1792),
                            FirstName = "Ella",
                            LastName = "Anderson",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = 20,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1795),
                            FirstName = "Alexander",
                            LastName = "Brown",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1795)
                        },
                        new
                        {
                            Id = 21,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1797),
                            FirstName = "Oliver",
                            LastName = "Garcia",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1797)
                        },
                        new
                        {
                            Id = 22,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1799),
                            FirstName = "Mia",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1800)
                        },
                        new
                        {
                            Id = 23,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1802),
                            FirstName = "William",
                            LastName = "Gonzalez",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1803)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sumqayit City",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1594),
                            FirstName = "Ali",
                            LastName = "Muradov",
                            Phone = "0555555555",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1595)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Istanbul",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1597),
                            FirstName = "Ayse",
                            LastName = "Kara",
                            Phone = "0555123456",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1597)
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1599),
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "0555234567",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1600)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1601),
                            FirstName = "Sophia",
                            LastName = "Smith",
                            Phone = "0555345678",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1602)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1604),
                            FirstName = "John",
                            LastName = "Johnson",
                            Phone = "0555456789",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1604)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1606),
                            FirstName = "Emma",
                            LastName = "Wilson",
                            Phone = "0555567890",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1610)
                        },
                        new
                        {
                            Id = 7,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1612),
                            FirstName = "Michael",
                            LastName = "Harris",
                            Phone = "0555678901",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1612)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1614),
                            FirstName = "Olivia",
                            LastName = "Davis",
                            Phone = "0555789012",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1615)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1617),
                            FirstName = "Lucas",
                            LastName = "Miller",
                            Phone = "0555890123",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1617)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1619),
                            FirstName = "Ava",
                            LastName = "Clark",
                            Phone = "0555101234",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 774, DateTimeKind.Local).AddTicks(1619)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .IsUnique();

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9794),
                            EndPoint = "Liverpool",
                            Passengers = 10,
                            StartPoint = "Manchester",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9794)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9797),
                            EndPoint = "Birmingham",
                            Passengers = 15,
                            StartPoint = "London",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9797)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9799),
                            EndPoint = "Edinburgh",
                            Passengers = 12,
                            StartPoint = "Glasgow",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9799)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9801),
                            EndPoint = "Boston",
                            Passengers = 8,
                            StartPoint = "New York",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9802)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9804),
                            EndPoint = "San Francisco",
                            Passengers = 20,
                            StartPoint = "Los Angeles",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9804)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9806),
                            EndPoint = "Amsterdam",
                            Passengers = 16,
                            StartPoint = "Paris",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9806)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9808),
                            EndPoint = "Melbourne",
                            Passengers = 18,
                            StartPoint = "Sydney",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9809)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9810),
                            EndPoint = "Munich",
                            Passengers = 14,
                            StartPoint = "Berlin",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9811)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9813),
                            EndPoint = "Osaka",
                            Passengers = 11,
                            StartPoint = "Tokyo",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9813)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9815),
                            EndPoint = "Florence",
                            Passengers = 9,
                            StartPoint = "Rome",
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(9815)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            ClassId = 1,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2612),
                            FirstName = "Elgun",
                            LastName = "Haqverdiyev",
                            ParentId = 1,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2613)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            ClassId = 2,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2615),
                            FirstName = "Alice",
                            LastName = "Johnson",
                            ParentId = 2,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2616)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            ClassId = 3,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2618),
                            FirstName = "John",
                            LastName = "Smith",
                            ParentId = 3,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2618)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            ClassId = 4,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2620),
                            FirstName = "Emily",
                            LastName = "Wilson",
                            ParentId = 4,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2621)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            ClassId = 5,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2623),
                            FirstName = "David",
                            LastName = "Brown",
                            ParentId = 5,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2623)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            ClassId = 6,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2625),
                            FirstName = "Sophia",
                            LastName = "Miller",
                            ParentId = 6,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2626)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            ClassId = 7,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2627),
                            FirstName = "Oliver",
                            LastName = "Davis",
                            ParentId = 7,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2628)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            ClassId = 8,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2630),
                            FirstName = "Lily",
                            LastName = "Garcia",
                            ParentId = 8,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2630)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            ClassId = 9,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2633),
                            FirstName = "Ethan",
                            LastName = "Martinez",
                            ParentId = 9,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2633)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            ClassId = 10,
                            Created = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2635),
                            FirstName = "Ava",
                            LastName = "Clark",
                            ParentId = 10,
                            Updated = new DateTime(2023, 11, 6, 15, 57, 40, 773, DateTimeKind.Local).AddTicks(2636)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.HasOne("Entity.Concrete.Driver", "Driver")
                        .WithOne("Car")
                        .HasForeignKey("Entity.Concrete.Car", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithOne("Ride")
                        .HasForeignKey("Entity.Concrete.Ride", "BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithMany("Students")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Class");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Navigation("Ride")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
