// <auto-generated />
using System;
using Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(SchoolBusDB))]
    [Migration("20231110062552_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6772),
                            Password = "admin",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6776),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6169),
                            DriverId = 1,
                            Number = "01-AA-001",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6169)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 18,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6178),
                            DriverId = 2,
                            Number = "02-BB-002",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6178)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6187),
                            DriverId = 3,
                            Number = "03-CC-003",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6187)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 22,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6192),
                            DriverId = 4,
                            Number = "04-DD-004",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6196)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6201),
                            DriverId = 5,
                            Number = "05-EE-005",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6205)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 21,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6209),
                            DriverId = 6,
                            Number = "06-FF-006",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6214)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 28,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6218),
                            DriverId = 7,
                            Number = "07-GG-007",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6223)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 24,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6227),
                            DriverId = 8,
                            Number = "08-HH-008",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6227)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 19,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6236),
                            DriverId = 9,
                            Number = "09-II-009",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6236)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 15,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6245),
                            DriverId = 10,
                            Number = "10-JJ-010",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(6245)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7044),
                            Name = "ZU-051",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7057),
                            Name = "ZU-052",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7057)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7062),
                            Name = "ZU-053",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7066)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7071),
                            Name = "ZU-054",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7075)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7080),
                            Name = "ZU-055",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7080)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7089),
                            Name = "ZU-056",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7089)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7093),
                            Name = "ZU-057",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7097)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7102),
                            Name = "ZU-058",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7106)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7111),
                            Name = "ZU-059",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7111)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7120),
                            Name = "ZU-060",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7120)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7579),
                            FirstName = "Daniel",
                            LastName = "Cormier",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7584)
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7588),
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7593)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7597),
                            FirstName = "Emily",
                            LastName = "Smith",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7602)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7606),
                            FirstName = "John",
                            LastName = "Brown",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7611)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7615),
                            FirstName = "Olivia",
                            LastName = "Miller",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7620)
                        },
                        new
                        {
                            Id = 6,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7624),
                            FirstName = "Lucas",
                            LastName = "Davis",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7629)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7633),
                            FirstName = "Ava",
                            LastName = "Garcia",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7633)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7642),
                            FirstName = "Liam",
                            LastName = "Martinez",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7642)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7651),
                            FirstName = "Mia",
                            LastName = "Clark",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7651)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7660),
                            FirstName = "Noah",
                            LastName = "Taylor",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7660)
                        },
                        new
                        {
                            Id = 11,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7669),
                            FirstName = "Sophia",
                            LastName = "Walker",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7669)
                        },
                        new
                        {
                            Id = 12,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7678),
                            FirstName = "William",
                            LastName = "White",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7678)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7687),
                            FirstName = "Emma",
                            LastName = "Jones",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7687)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7691),
                            FirstName = "James",
                            LastName = "Wilson",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7695)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7700),
                            FirstName = "Isabella",
                            LastName = "Jackson",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7704)
                        },
                        new
                        {
                            Id = 16,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7709),
                            FirstName = "Benjamin",
                            LastName = "Harris",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7713)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7718),
                            FirstName = "Lucy",
                            LastName = "Turner",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7718)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7727),
                            FirstName = "Logan",
                            LastName = "Smith",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7727)
                        },
                        new
                        {
                            Id = 19,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7736),
                            FirstName = "Ella",
                            LastName = "Anderson",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7736)
                        },
                        new
                        {
                            Id = 20,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7745),
                            FirstName = "Alexander",
                            LastName = "Brown",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7745)
                        },
                        new
                        {
                            Id = 21,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7749),
                            FirstName = "Oliver",
                            LastName = "Garcia",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7753)
                        },
                        new
                        {
                            Id = 22,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7758),
                            FirstName = "Mia",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7762)
                        },
                        new
                        {
                            Id = 23,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7767),
                            FirstName = "William",
                            LastName = "Gonzalez",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7771)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sumqayit City",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7231),
                            FirstName = "Ali",
                            LastName = "Muradov",
                            Phone = "0555555555",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7236)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Istanbul",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7245),
                            FirstName = "Ayse",
                            LastName = "Kara",
                            Phone = "0555123456",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7245)
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7254),
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "0555234567",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7254)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7263),
                            FirstName = "Sophia",
                            LastName = "Smith",
                            Phone = "0555345678",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7263)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7272),
                            FirstName = "John",
                            LastName = "Johnson",
                            Phone = "0555456789",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7272)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7276),
                            FirstName = "Emma",
                            LastName = "Wilson",
                            Phone = "0555567890",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7280)
                        },
                        new
                        {
                            Id = 7,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7285),
                            FirstName = "Michael",
                            LastName = "Harris",
                            Phone = "0555678901",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7289)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7294),
                            FirstName = "Olivia",
                            LastName = "Davis",
                            Phone = "0555789012",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7298)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7303),
                            FirstName = "Lucas",
                            LastName = "Miller",
                            Phone = "0555890123",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7307)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7312),
                            FirstName = "Ava",
                            LastName = "Clark",
                            Phone = "0555101234",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(7316)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .IsUnique();

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4893),
                            EndPoint = "Liverpool",
                            Passengers = 10,
                            StartPoint = "Manchester",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4897)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4902),
                            EndPoint = "Birmingham",
                            Passengers = 15,
                            StartPoint = "London",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4906)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4911),
                            EndPoint = "Edinburgh",
                            Passengers = 12,
                            StartPoint = "Glasgow",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4915)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4920),
                            EndPoint = "Boston",
                            Passengers = 8,
                            StartPoint = "New York",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4924)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4929),
                            EndPoint = "San Francisco",
                            Passengers = 20,
                            StartPoint = "Los Angeles",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4933)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4938),
                            EndPoint = "Amsterdam",
                            Passengers = 16,
                            StartPoint = "Paris",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4938)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4947),
                            EndPoint = "Melbourne",
                            Passengers = 18,
                            StartPoint = "Sydney",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4947)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4955),
                            EndPoint = "Munich",
                            Passengers = 14,
                            StartPoint = "Berlin",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4955)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4964),
                            EndPoint = "Osaka",
                            Passengers = 11,
                            StartPoint = "Tokyo",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4964)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4969),
                            EndPoint = "Florence",
                            Passengers = 9,
                            StartPoint = "Rome",
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 662, DateTimeKind.Local).AddTicks(4973)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            ClassId = 1,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6289),
                            FirstName = "Elgun",
                            LastName = "Haqverdiyev",
                            ParentId = 1,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6289)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            ClassId = 2,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6298),
                            FirstName = "Alice",
                            LastName = "Johnson",
                            ParentId = 2,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6303)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            ClassId = 3,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6307),
                            FirstName = "John",
                            LastName = "Smith",
                            ParentId = 3,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6312)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            ClassId = 4,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6316),
                            FirstName = "Emily",
                            LastName = "Wilson",
                            ParentId = 4,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6321)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            ClassId = 5,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6325),
                            FirstName = "David",
                            LastName = "Brown",
                            ParentId = 5,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6325)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            ClassId = 6,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6334),
                            FirstName = "Sophia",
                            LastName = "Miller",
                            ParentId = 6,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6334)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            ClassId = 7,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6343),
                            FirstName = "Oliver",
                            LastName = "Davis",
                            ParentId = 7,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6343)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            ClassId = 8,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6352),
                            FirstName = "Lily",
                            LastName = "Garcia",
                            ParentId = 8,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6352)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            ClassId = 9,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6361),
                            FirstName = "Ethan",
                            LastName = "Martinez",
                            ParentId = 9,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6361)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            ClassId = 10,
                            Created = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6365),
                            FirstName = "Ava",
                            LastName = "Clark",
                            ParentId = 10,
                            Updated = new DateTime(2023, 11, 9, 22, 25, 51, 661, DateTimeKind.Local).AddTicks(6370)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.HasOne("Entity.Concrete.Driver", "Driver")
                        .WithOne("Car")
                        .HasForeignKey("Entity.Concrete.Car", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithOne("Ride")
                        .HasForeignKey("Entity.Concrete.Ride", "BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithMany("Students")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Class");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Navigation("Ride")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
