// <auto-generated />
using System;
using Context.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(SchoolBusDB))]
    [Migration("20231101104645_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5425),
                            Password = "admin",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5426),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5300),
                            DriverId = 1,
                            Number = "01-AA-001",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5301)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 18,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5303),
                            DriverId = 2,
                            Number = "02-BB-002",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5304)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5306),
                            DriverId = 3,
                            Number = "03-CC-003",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5306)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 22,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5308),
                            DriverId = 4,
                            Number = "04-DD-004",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5308)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5311),
                            DriverId = 5,
                            Number = "05-EE-005",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5311)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 21,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5313),
                            DriverId = 6,
                            Number = "06-FF-006",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5314)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 28,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5315),
                            DriverId = 7,
                            Number = "07-GG-007",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5316)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 24,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5317),
                            DriverId = 8,
                            Number = "08-HH-008",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5318)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 19,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5320),
                            DriverId = 9,
                            Number = "09-II-009",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5320)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 15,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5322),
                            DriverId = 10,
                            Number = "10-JJ-010",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5322)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5618),
                            Name = "ZU-051",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5618)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5620),
                            Name = "ZU-052",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5621)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5623),
                            Name = "ZU-053",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5623)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5625),
                            Name = "ZU-054",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5625)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5627),
                            Name = "ZU-055",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5627)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5629),
                            Name = "ZU-056",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5629)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5631),
                            Name = "ZU-057",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5632)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5633),
                            Name = "ZU-058",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5634)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5636),
                            Name = "ZU-059",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5636)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5638),
                            Name = "ZU-060",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5638)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5806),
                            FirstName = "Daniel",
                            LastName = "Cormier",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5807)
                        },
                        new
                        {
                            Id = 2,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5810),
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5810)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5812),
                            FirstName = "Emily",
                            LastName = "Smith",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5813)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5815),
                            FirstName = "John",
                            LastName = "Brown",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5815)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5817),
                            FirstName = "Olivia",
                            LastName = "Miller",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5818)
                        },
                        new
                        {
                            Id = 6,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5820),
                            FirstName = "Lucas",
                            LastName = "Davis",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5821)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5822),
                            FirstName = "Ava",
                            LastName = "Garcia",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5823)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5825),
                            FirstName = "Liam",
                            LastName = "Martinez",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5825)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5827),
                            FirstName = "Mia",
                            LastName = "Clark",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5828)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5830),
                            FirstName = "Noah",
                            LastName = "Taylor",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5830)
                        },
                        new
                        {
                            Id = 11,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5833),
                            FirstName = "Sophia",
                            LastName = "Walker",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5834)
                        },
                        new
                        {
                            Id = 12,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5835),
                            FirstName = "William",
                            LastName = "White",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5836)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5838),
                            FirstName = "Emma",
                            LastName = "Jones",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5838)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5840),
                            FirstName = "James",
                            LastName = "Wilson",
                            Phone = "0509892345",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5841)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5844),
                            FirstName = "Isabella",
                            LastName = "Jackson",
                            Phone = "0509896789",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5845)
                        },
                        new
                        {
                            Id = 16,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5847),
                            FirstName = "Benjamin",
                            LastName = "Harris",
                            Phone = "0509894321",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5847)
                        },
                        new
                        {
                            Id = 17,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5849),
                            FirstName = "Lucy",
                            LastName = "Turner",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5849)
                        },
                        new
                        {
                            Id = 18,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5851),
                            FirstName = "Logan",
                            LastName = "Smith",
                            Phone = "0509892109",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5852)
                        },
                        new
                        {
                            Id = 19,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5854),
                            FirstName = "Ella",
                            LastName = "Anderson",
                            Phone = "0509895432",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5855)
                        },
                        new
                        {
                            Id = 20,
                            Address = "Denver",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5857),
                            FirstName = "Alexander",
                            LastName = "Brown",
                            Phone = "0509898765",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5857)
                        },
                        new
                        {
                            Id = 21,
                            Address = "San-Francisco",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5859),
                            FirstName = "Oliver",
                            LastName = "Garcia",
                            Phone = "0509891232",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5859)
                        },
                        new
                        {
                            Id = 22,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5861),
                            FirstName = "Mia",
                            LastName = "Johnson",
                            Phone = "0509894567",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5862)
                        },
                        new
                        {
                            Id = 23,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5863),
                            FirstName = "William",
                            LastName = "Gonzalez",
                            Phone = "0509897890",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5864)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sumqayit City",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5717),
                            FirstName = "Ali",
                            LastName = "Muradov",
                            Phone = "0555555555",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5718)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Istanbul",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5720),
                            FirstName = "Ayse",
                            LastName = "Kara",
                            Phone = "0555123456",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5721)
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5722),
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "0555234567",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5723)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Los Angeles",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5725),
                            FirstName = "Sophia",
                            LastName = "Smith",
                            Phone = "0555345678",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5726)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Chicago",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5727),
                            FirstName = "John",
                            LastName = "Johnson",
                            Phone = "0555456789",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5728)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Miami",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5730),
                            FirstName = "Emma",
                            LastName = "Wilson",
                            Phone = "0555567890",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5730)
                        },
                        new
                        {
                            Id = 7,
                            Address = "San Diego",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5732),
                            FirstName = "Michael",
                            LastName = "Harris",
                            Phone = "0555678901",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5733)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Seattle",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5735),
                            FirstName = "Olivia",
                            LastName = "Davis",
                            Phone = "0555789012",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5735)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Boston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5737),
                            FirstName = "Lucas",
                            LastName = "Miller",
                            Phone = "0555890123",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5737)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Houston",
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5739),
                            FirstName = "Ava",
                            LastName = "Clark",
                            Phone = "0555101234",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(5740)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId")
                        .IsUnique();

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4250),
                            EndPoint = "Liverpool",
                            Passengers = 10,
                            StartPoint = "Manchester",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4250)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4253),
                            EndPoint = "Birmingham",
                            Passengers = 15,
                            StartPoint = "London",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4253)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4256),
                            EndPoint = "Edinburgh",
                            Passengers = 12,
                            StartPoint = "Glasgow",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4256)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4258),
                            EndPoint = "Boston",
                            Passengers = 8,
                            StartPoint = "New York",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4259)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4260),
                            EndPoint = "San Francisco",
                            Passengers = 20,
                            StartPoint = "Los Angeles",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4261)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4263),
                            EndPoint = "Amsterdam",
                            Passengers = 16,
                            StartPoint = "Paris",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4263)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4265),
                            EndPoint = "Melbourne",
                            Passengers = 18,
                            StartPoint = "Sydney",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4266)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4267),
                            EndPoint = "Munich",
                            Passengers = 14,
                            StartPoint = "Berlin",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4268)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4270),
                            EndPoint = "Osaka",
                            Passengers = 11,
                            StartPoint = "Tokyo",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4270)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4272),
                            EndPoint = "Florence",
                            Passengers = 9,
                            StartPoint = "Rome",
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 216, DateTimeKind.Local).AddTicks(4273)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            ClassId = 1,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7025),
                            FirstName = "Elgun",
                            LastName = "Haqverdiyev",
                            ParentId = 1,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7026)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            ClassId = 2,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7029),
                            FirstName = "Alice",
                            LastName = "Johnson",
                            ParentId = 2,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7029)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            ClassId = 3,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7031),
                            FirstName = "John",
                            LastName = "Smith",
                            ParentId = 3,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7032)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            ClassId = 4,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7034),
                            FirstName = "Emily",
                            LastName = "Wilson",
                            ParentId = 4,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7034)
                        },
                        new
                        {
                            Id = 5,
                            BusId = 5,
                            ClassId = 5,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7036),
                            FirstName = "David",
                            LastName = "Brown",
                            ParentId = 5,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7037)
                        },
                        new
                        {
                            Id = 6,
                            BusId = 6,
                            ClassId = 6,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7038),
                            FirstName = "Sophia",
                            LastName = "Miller",
                            ParentId = 6,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7039)
                        },
                        new
                        {
                            Id = 7,
                            BusId = 7,
                            ClassId = 7,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7041),
                            FirstName = "Oliver",
                            LastName = "Davis",
                            ParentId = 7,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7041)
                        },
                        new
                        {
                            Id = 8,
                            BusId = 8,
                            ClassId = 8,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7043),
                            FirstName = "Lily",
                            LastName = "Garcia",
                            ParentId = 8,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7044)
                        },
                        new
                        {
                            Id = 9,
                            BusId = 9,
                            ClassId = 9,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7045),
                            FirstName = "Ethan",
                            LastName = "Martinez",
                            ParentId = 9,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7046)
                        },
                        new
                        {
                            Id = 10,
                            BusId = 10,
                            ClassId = 10,
                            Created = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7048),
                            FirstName = "Ava",
                            LastName = "Clark",
                            ParentId = 10,
                            Updated = new DateTime(2023, 11, 1, 14, 46, 45, 215, DateTimeKind.Local).AddTicks(7049)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.HasOne("Entity.Concrete.Driver", "Driver")
                        .WithOne("Car")
                        .HasForeignKey("Entity.Concrete.Car", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Entity.Concrete.Ride", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithOne("Ride")
                        .HasForeignKey("Entity.Concrete.Ride", "BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Entity.Concrete.Student", b =>
                {
                    b.HasOne("Entity.Concrete.Car", "Car")
                        .WithMany("Students")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Class");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entity.Concrete.Car", b =>
                {
                    b.Navigation("Ride")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity.Concrete.Driver", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.Concrete.Parent", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
